// Offline fallback questions for couples
// Used when Supabase connection fails
export const FALLBACK_QUESTIONS: string[] = [
  "What's your favorite memory we've made together?",
  "If we could travel anywhere tomorrow, where would you want to go?",
  "What song reminds you of us?",
  "What's one thing I do that always makes you smile?",
  "What did you think when you first saw me?",
  "If we had a whole day with no plans, what would you want to do?",
  "What's your favorite meal we've shared together?",
  "What's a small thing I do that you really appreciate?",
  "What's one thing on your couple bucket list?",
  "What's the funniest moment we've had together?",
  "If you could relive one day with me, which would it be?",
  "What's something new you'd like us to try together?",
  "What's your love language, and do I speak it well?",
  "What's the best gift you've ever received from me?",
  "If we were characters in a movie, what genre would it be?",
  "What's one habit of mine that you find adorable?",
  "Where do you see us in five years?",
  "What's something you've learned from being with me?",
  "What's your favorite way to spend a lazy Sunday with me?",
  "If you could describe our relationship in three words, what would they be?",
  "What's the most thoughtful thing I've done for you?",
  "What's a dream date you'd love for us to go on?",
  "What's one thing you want to tell me but haven't yet?",
  "What's your favorite inside joke we have?",
  "If we opened a business together, what would it be?",
  "What's the best advice you'd give to other couples?",
  "What's a challenge we've overcome that made us stronger?",
  "What's the first thing you noticed about me?",
  "What's your favorite season to spend with me, and why?",
  "If you could pick a superpower for us to share, what would it be?",
  "What's one thing that always makes you feel loved by me?",
  "What's a place that feels like 'ours'?",
  "What's the most spontaneous thing we've done together?",
  "What's your favorite photo of us?",
  "If we could learn something new together, what would it be?",
];
